# Generated by Django 3.1.7 on 2021-03-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrowdLimit', models.IntegerField()),
                ('InputImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
