# Generated by Django 3.1.7 on 2021-05-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0002_auto_20210303_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countprediction',
            old_name='CrowCount',
            new_name='CrowdCount',
        ),
        migrations.RemoveField(
            model_name='countprediction',
            name='InputImage',
        ),
        migrations.AddField(
            model_name='countprediction',
            name='StartTime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
