# Generated by Django 3.1.7 on 2021-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0004_auto_20210511_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countprediction',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='countprediction',
            name='CDate',
            field=models.DateField(default='2001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='countprediction',
            name='CTime',
            field=models.TimeField(default='20:00', null=True),
        ),
    ]
