# Generated by Django 3.1.7 on 2021-05-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0005_auto_20210511_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopInfo',
            fields=[
                ('areaId', models.IntegerField(primary_key=True, serialize=False)),
                ('averageCount', models.IntegerField(default=0)),
                ('maxCount', models.IntegerField(default=0)),
                ('minCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='areaOneMin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaCount', models.IntegerField()),
                ('cDate', models.DateField(default='2001-01-01', null=True)),
                ('cTime', models.TimeField(default='20:00', null=True)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mscnn.shopinfo')),
            ],
        ),
        migrations.CreateModel(
            name='areaDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('cDate', models.DateField(default='2001-01-01', null=True)),
                ('cTime', models.TimeField(default='20:00', null=True)),
                ('maxTime', models.TimeField(default='20:00', null=True)),
                ('minTime', models.TimeField(default='20:00', null=True)),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mscnn.shopinfo')),
            ],
        ),
    ]
