# Generated by Django 3.1.7 on 2021-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0007_remove_areaday_ctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopinfo',
            old_name='maxCount',
            new_name='crowdLimit',
        ),
        migrations.RenameField(
            model_name='shopinfo',
            old_name='minCount',
            new_name='dayAvgCount',
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='monthAvgCount',
            field=models.IntegerField(default=0),
        ),
    ]
