# Generated by Django 3.1.7 on 2021-06-14 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0008_auto_20210525_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='crowdLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cDate', models.DateField(default='2001-01-01', null=True)),
                ('cTime', models.TimeField(default='20:00', null=True)),
                ('areaCount', models.IntegerField()),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mscnn.shopinfo')),
            ],
        ),
    ]
