# Generated by Django 3.1.7 on 2021-06-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscnn', '0009_crowdlimit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopinfo',
            old_name='crowdLimit',
            new_name='CrowdLimit',
        ),
    ]
